### ISSUE TITLE
F-636 Tras actualizar a rails7 en formulario de caso, pestaña acto no permite agregar acto por problema CSRF

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#637]
En traza queda:
```

W, [2022-01-07T06:44:49.232966 #46142]  WARN -- : [7dc34df9-6a80-4559-87a0-dc333098a0f9] Can't verify CSRF token authenticity.
I, [2022-01-07T06:44:49.233363 #46142]  INFO -- : [7dc34df9-6a80-4559-87a0-dc333098a0f9] Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Alloca
tions: 362)                                                                                                                                                     
F, [2022-01-07T06:44:49.235160 #46142] FATAL -- : [7dc34df9-6a80-4559-87a0-dc333098a0f9]                                       
[7dc34df9-6a80-4559-87a0-dc333098a0f9] ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):     
[7dc34df9-6a80-4559-87a0-dc333098a0f9]                                                                                                                          
[7dc34df9-6a80-4559-87a0-dc333098a0f9] actionpack (7.0.0) lib/action_controller/metal/request_forgery_protection.rb:251:in `handle_unverified_request'
[7dc34df9-6a80-4559-87a0-dc333098a0f9] actionpack (7.0.0) lib/action_controller/metal/request_forgery_protection.rb:284:in `handle_unverified_request'
[7dc34df9-6a80-4559-87a0-dc333098a0f9] devise (4.8.1) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
```

**Comment by vtamara** [comment]
No se encuentra un problema similar en https://github.com/rails/rails/issues?q=is%3Aissue+is%3Aopen+CSRF

**Comment by vtamara** [comment]
Tras revisar https://samuelmullen.com/articles/csrf-protection-and-ruby-on-rails/ e intentar agregando en sivel2_gen aen `app/controllers/sivel2_gen/actos_controller.rb ` la línea
```
protect_from_forgery with: :null_session  
```
Se ve que agrega acto.  Nos parece que sería mejor que el envio se haga empleando el token CSRF.

**Comment by vtamara** [comment]
Se intenta usando la función global sip_enviarautomatico_formulario que ya agrega el token CSRF.
Se intenta mejorandola minimamente.
Sería mejor opción usar una nueva función en javascript puro.

**Comment by vtamara** [comment]
Se resuelve agregando explícito el token.
