### ISSUE TITLE
F-844 En sitio de producción no permite autocompletar víctimas nuevas

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#844]
Con firefox al empezar a escribir presenta con cuadro de autocompeltación de jquery-ui los nombres pero al elegir uno no cambia a la persona del caso.

Con chrome si presenta el control de autocompletación con datalist, pero al elegir uno no completa.  En consola sale el error 
```
recursos_sprockets-bda4b16ced94d36d4f149c127e60a46afe5da8f6ab4fe139c175688ad3921a4d.js:3529 Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at Object.success (recursos_sprockets-bda4b16ced94d36d4f149c127e60a46afe5da8f6ab4fe139c175688ad3921a4d.js:3529:31)
    at rails-ujs.js:203:23
    at xhr.onreadystatechange (rails-ujs.js:255:20)
```

**Comment by vtamara** [comment]
En apo215 se sobrecargó la funcioń remplaza de personas_controller dañando la funcionalidad de autocompletar víctima.

**Comment by vtamara** [comment]
Para sobrellevar se renombar la función remplazar de personas_controller en apo214 por remplazar_apo214 y se crea incidente para arreglar autocompletación en apo214.
